Me add readme
ong-bitcoin-argentina/DIDI-SSI-App_sdk pull request #72
Opened 2022-10-19 19:58 UTC by farpires

DIDI-SSI-App_sdk:

Se agregó el Readme.md

2022-10-25 11:35 UTC, claudio-uslenghi commented on README.md
> +For more information, see the [documentation](https://docs.didi.org.ar/docs/developers/solucion/descripcion-tecnica/arquitectura-issuer)
Quizas aqui se pueda linkear a https://docs.didi.org.ar/docs/aidi/aidi-descripcion

2022-10-25 11:35 UTC, claudio-uslenghi requested changes
La lista de funcinalidades quedaron en una linea sola 
![image](https://user-images.githubusercontent.com/12357740/197762666-55904d8d-7e75-44a8-a0e6-b68938845ecf.png)

![image](https://user-images.githubusercontent.com/12357740/197762803-fcd28e82-9884-4992-be2e-5ac837637636.png)

2022-10-26 16:11 UTC, farpires reviewed
example: 
![image](https://user-images.githubusercontent.com/55299077/198074938-2a3daf66-8447-4a73-99e1-b1b51de9c29e.png)

code: https://github.com/ong-bitcoin-argentina/DIDI-SSI-Docs/blob/master/docs/developers/solucion/descripcion-tecnica/delegation.md?plain=1

output : https://github.com/ong-bitcoin-argentina/DIDI-SSI-Docs/blob/master/docs/developers/solucion/descripcion-tecnica/delegation.md

2022-10-26 17:47 UTC, claudio-uslenghi approved these changes

2022-10-26 17:47 UTC, merged